name: Bug 反馈
description: 为 echarts-enhanced-completion 提交一个 bug 反馈
title: "[Bug] "
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      这个 Issue 是专门用于 bug 反馈的。

      您可以尝试在 Issue 中搜索您的问题 - 它可能已经在开发分支中得到解答甚至修复。 但是，如果您发现一个旧的、已关闭的问题在最新版本中仍然存在，您应该使用下面的表单打开一个新问题，而不是对旧问题发表评论。

      对于 echarts 的使用问题, 请参考下面的资源:

      - Read the [docs](https://echarts.apache.org/option.html)
      - Find in [examples](https://echarts.apache.org/examples/)
      - Look for / ask questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/echarts)

- type: input
  attributes:
    label: 版本
    description: |
      检查该问题是否可以使用最新的稳定版本重现。
    placeholder: |
      e.g. 1.3.9

  validations:
    required: true

- type: dropdown
  attributes:
    label: 文件类型
    description: |
      您使用的是什么类型的文件？
    options:
      - html
      - javascript
      - typescript
      - vue

  validations:
    required: true

- type: textarea
  attributes:
    label: 重现步骤
    description: |
      清晰简洁的重现说明对于我们能够及时对您的问题进行分类非常重要。 请注意，您可以使用 [Markdown](https://guides.github.com/features/mastering-markdown/) 来格式化列表和代码。

    placeholder: |
      1. 您是如何创建选项的。
      2. 错误发生前的用户交互。

  validations:
    required: true

- type: textarea
  attributes:
    label: 当前行为
    description: 对您所经历的情况的简明描述。
  validations:
    required: true

- type: textarea
  attributes:
    label: 预期行为
    description: 对您期望发生的事情的简要描述。
  validations:
    required: true

- type: textarea
  attributes:
    label: 环境
    description: |
      e.g.
        - **OS**: Windows 10
    value: |
        - **OS**:
    render: markdown

  validations:
    required: false

- type: textarea
  attributes:
    label: 有什么补充意见吗？
    description: |
      e.g. 您如何遇到此错误的一些背景/上下文。

  validations:
    required: false