name: 新功能请求
description: 为 echarts-enhanced-completion 请求新功能 
title: "[Feature] "
labels: [feature]
body:
- type: markdown
  attributes:
    value: |
      这个 Issues 是专门用于新功能请求的。

      您可以尝试在 Issue 中搜索您的问题 - 它可能已经在开发分支中得到解答。 

- type: textarea
  attributes:
    label: 这个功能解决了什么问题？
    description: |
      解释此功能请求背后的用例、上下文和基本原理。 更重要的是，您尝试构建的最终用户体验是什么，才导致需要此功能？

  validations:
    required: true